### ISSUE TITLE
Regarding the table scrolling on mobile devices

### ISSUE THREAD

**Issue by Regnander** [Spidersouris/termic#1]
It's currently only possible to scroll the search result tables on mobile devices by swiping on the table header (area with green border) instead of the table body (area with blue border). I'm guessing this isn't the indented behavior.

OS: Android 11
Browser: Edge, Firefox and Chrome

![Screenshot](https://github.com/Spidersouris/termic/assets/17113053/bca690a0-d698-4ba5-9ea3-4226725cd90e)

**Comment by spidersouris** [comment]
Thanks for the report! I'll push a quick fix early next week.

**Comment by spidersouris** [comment]
Apologies for the delay in pushing the fix -- can you check if it works now? I've also changed the copy behaviour slightly so that it requires a two-finger tap now instead of a double tap, which should prevent unwanted copies. Let me know what you think.

**Comment by Regnander** [comment]
The table scrolling works fine now. Thank you!

Regarding the copy behavior, I personally never use that functionality since it gives me the whole table row while I'm only really interested in the text inside the _Translation_ column.
