### ISSUE TITLE
bug: KeyError: 'TERMIC_MAIL_SERVER'

### ISSUE THREAD

**Issue by damufo** [Spidersouris/termic#8]
Ubuntu 22.04

```
git clone https://github.com/spidersouris/termic.git
cd termic/
python3 -m venv .venv
source .venv/bin/activate
sudo apt install libpq-dev (https://github.com/spidersouris/termic/issues/7#issue-2628458824)
pip install -r requirements.txt
python termic.py 
```

```
± |main ?:1 ✗| → python termic.py 
Traceback (most recent call last):
  File "/home/damufo/dev/termic/termic.py", line 8, in <module>
    from config.mail_config import Config
  File "/home/damufo/dev/termic/config/mail_config.py", line 3, in <module>
    class Config:
  File "/home/damufo/dev/termic/config/mail_config.py", line 4, in Config
    MAIL_SERVER = os.environ["TERMIC_MAIL_SERVER"]
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'TERMIC_MAIL_SERVER'
```

**Comment by spidersouris** [comment]
Hi! Sorry for the late reply. I will make changes to how env vars are used/loaded for people who want to run their own version of termic. Will take a look this weekend.

**Comment by damufo** [comment]
OK! 🙂
Very thanks!!

**Comment by spidersouris** [comment]
You should now be able to run termic without having to specify a mail config. If some critical mail key is missing, the mail feature will be disabled. I have updated the README to reflect this. Please let me know if everything works as expected!

**Comment by damufo** [comment]
Not wor for me.
git pull and after:

 |.venv|py-3.10.12 mybook in ~/dev/termic
± |main ?:3 ✗| → python termic.py 
  File "/home/myuser/dev/termic/termic.py", line 26
    f"The following keys are missing: {", ".join(missing_keys)}"
                                        ^
SyntaxError: f-string: expecting '}'

 |.venv|py-3.10.12 mybook in ~/dev/termic

**Comment by spidersouris** [comment]
argh, this is because I tested using Python 3.12 (which supports nested quotes for f-strings). Should be fixed now with https://github.com/spidersouris/termic/commit/ce43457d7188522262f5cd893dff20f9a629bfb1, can you try?

**Comment by damufo** [comment]
Very thanks! 🙂
Now start.
But not work,  database not exists. That is no error,  documentation on how to set up a sample database would be missing.
 I open another issue. 🙂
